"""Added more to database

Revision ID: 3859aaa90dd2
Revises: 
Create Date: 2024-12-04 13:44:45.441542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3859aaa90dd2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('late_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_date', sa.DateTime(), nullable=False),
    sa.Column('state_code', sa.String(length=10), nullable=False),
    sa.Column('request_type', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('late_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_late_log_state_code'), ['state_code'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('middle_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('state_code', sa.String(length=10), nullable=False),
    sa.Column('registration_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('state_code')
    )
    op.create_table('attendance_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('sign_in_time', sa.Time(), nullable=False),
    sa.Column('meeting_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attendance_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attendance_log_meeting_date'), ['meeting_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attendance_log_meeting_date'))

    op.drop_table('attendance_log')
    op.drop_table('users')
    with op.batch_alter_table('late_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_late_log_state_code'))

    op.drop_table('late_log')
    # ### end Alembic commands ###
