"""Updated AdminSettings model

Revision ID: cda5be67dec5
Revises: 75c471f11146
Create Date: 2024-12-10 17:06:47.166381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cda5be67dec5'
down_revision = '75c471f11146'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admin_settings')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_settings',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('early_arrival_start', sa.TIME(), nullable=True),
    sa.Column('late_arrival_start', sa.TIME(), nullable=True),
    sa.Column('late_arrival_end', sa.TIME(), nullable=True),
    sa.Column('lateness_fine', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('monthly_due', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('account_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('account_number', sa.VARCHAR(length=20), nullable=True),
    sa.Column('bank_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('admin_username', sa.VARCHAR(length=100), nullable=True),
    sa.Column('admin_password', sa.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
