"""Added AdminSettings database and fixed some issues

Revision ID: e6e005767339
Revises: 3859aaa90dd2
Create Date: 2024-12-10 16:14:05.575479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6e005767339'
down_revision = '3859aaa90dd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('early_arrival_start', sa.Time(), nullable=True),
    sa.Column('late_arrival_start', sa.Time(), nullable=True),
    sa.Column('late_arrival_end', sa.Time(), nullable=True),
    sa.Column('lateness_fine', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('monthly_due', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('account_name', sa.String(length=100), nullable=True),
    sa.Column('account_number', sa.String(length=20), nullable=True),
    sa.Column('bank_name', sa.String(length=100), nullable=True),
    sa.Column('admin_username', sa.String(length=100), nullable=True),
    sa.Column('admin_password', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('late_log', schema=None) as batch_op:
        batch_op.alter_column('transaction_date',
               existing_type=sa.DATETIME(),
               type_=sa.Date(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('late_log', schema=None) as batch_op:
        batch_op.alter_column('transaction_date',
               existing_type=sa.Date(),
               type_=sa.DATETIME(),
               existing_nullable=False)

    op.drop_table('admin_settings')
    # ### end Alembic commands ###
