"""Added meeting day to AdminSettings

Revision ID: ef4fe06daa3d
Revises: 81bfaa03c854
Create Date: 2025-01-16 04:21:03.955280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef4fe06daa3d'
down_revision = '81bfaa03c854'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meeting_day', sa.String(length=20), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.String(length=10), server_default='N/A', nullable=False))
        batch_op.add_column(sa.Column('local_gov', sa.String(length=20), server_default='N/A', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('local_gov')
        batch_op.drop_column('gender')

    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_column('meeting_day')

    # ### end Alembic commands ###
